### ISSUE TITLE
Unhandled conformer generation failures

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openff-toolkit#1049]
**Describe the bug**

**To Reproduce**

```python3
>>> from openff.toolkit.utils.toolkits import OpenEyeToolkitWrapper, RDKitToolkitWrapper, AmberToolsToolkitWrapper, ToolkitRegistry
>>> from openff.toolkit.topology import Molecule
>>> molecule = Molecule.from_smiles(100*"CC")
```

Directly generating conformers with `RDKitToolkitWrapper` is just missed, leading to a confusing traceback:

```python3
>>> molecule.generate_conformers(n_conformers=1, toolkit_registry=RDKitToolkitWrapper())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mwt/software/openforcefield/openff/toolkit/topology/molecule.py", line 3230, in generate_conformers
    return toolkit.generate_conformers(
  File "/Users/mwt/software/openforcefield/openff/toolkit/utils/rdkit_wrapper.py", line 898, in generate_conformers
    for conformer in molecule2._conformers:
TypeError: 'NoneType' object is not iterable
```

It's caught with OpenEye:

```python3
>>> molecule.generate_conformers(n_conformers=1, toolkit_registry=OpenEyeToolkitWrapper())
Warning: : Failed to build structure from CT
Warning: : Failed to build structure from CT
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mwt/software/openforcefield/openff/toolkit/topology/molecule.py", line 3230, in generate_conformers
    return toolkit.generate_conformers(
  File "/Users/mwt/software/openforcefield/openff/toolkit/utils/openeye_wrapper.py", line 1692, in generate_conformers
    raise Exception("OpenEye Omega conformer generation failed")
Exception: OpenEye Omega conformer generation failed
```

This is descriptive, but it's also the most general `Exception` and would be tricky to capture as a downstream user.

This can affect charge assignment:

```python3
>>> molecule.assign_partial_charges(partial_charge_method='am1bcc')
Warning: : Failed to build structure from CT
Warning: : Failed to build structure from CT
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mwt/software/openforcefield/openff/toolkit/topology/molecule.py", line 3439, in assign_partial_charges
    toolkit_registry.call(
  File "/Users/mwt/software/openforcefield/openff/toolkit/utils/toolkit_registry.py", line 380, in call
    raise ValueError(msg)
ValueError: No registered toolkits can provide the capability "assign_partial_charges" for args "()" and kwargs "{'molecule': Molecule with name '' and SMILES '[H]C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])[H]', 'partial_charge_method': 'am1bcc', 'use_conformers': None, 'strict_n_conformers': False, 'normalize_partial_charges': True, '_cls': <class 'openff.toolkit.topology.molecule.Molecule'>}"
Available toolkits are: [ToolkitWrapper around OpenEye Toolkit version 2021.1.1, ToolkitWrapper around The RDKit version 2021.03.4, ToolkitWrapper around AmberTools version 21.0, ToolkitWrapper around Built-in Toolkit version None]
 ToolkitWrapper around OpenEye Toolkit version 2021.1.1 <class 'Exception'> : OpenEye Omega conformer generation failed
 ToolkitWrapper around The RDKit version 2021.03.4 <class 'openff.toolkit.utils.exceptions.ChargeMethodUnavailableError'> : partial_charge_method 'am1bcc' is not available from RDKitToolkitWrapper. Available charge methods are ['mmff94']
 ToolkitWrapper around AmberTools version 21.0 <class 'TypeError'> : 'NoneType' object is not iterable
 ToolkitWrapper around Built-in Toolkit version None <class 'openff.toolkit.utils.exceptions.ChargeMethodUnavailableError'> : Partial charge method "am1bcc"" is not supported by the Built-in toolkit. Available charge methods are ['zeros', 'formal_charge']
>>> molecule.assign_partial_charges(partial_charge_method='am1bcc', toolkit_registry=ToolkitRegistry([AmberToolsToolkitWrapper, RDKitToolkitWrapper]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mwt/software/openforcefield/openff/toolkit/topology/molecule.py", line 3439, in assign_partial_charges
    toolkit_registry.call(
  File "/Users/mwt/software/openforcefield/openff/toolkit/utils/toolkit_registry.py", line 380, in call
    raise ValueError(msg)
ValueError: No registered toolkits can provide the capability "assign_partial_charges" for args "()" and kwargs "{'molecule': Molecule with name '' and SMILES '[H]C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])C([H])([H])[H]', 'partial_charge_method': 'am1bcc', 'use_conformers': None, 'strict_n_conformers': False, 'normalize_partial_charges': True, '_cls': <class 'openff.toolkit.topology.molecule.Molecule'>}"
Available toolkits are: [ToolkitWrapper around AmberTools version 21.0, ToolkitWrapper around The RDKit version 2021.03.4]
 ToolkitWrapper around AmberTools version 21.0 <class 'TypeError'> : 'NoneType' object is not iterable
 ToolkitWrapper around The RDKit version 2021.03.4 <class 'openff.toolkit.utils.exceptions.ChargeMethodUnavailableError'> : partial_charge_method 'am1bcc' is not available from RDKitToolkitWrapper. Available charge methods are ['mmff94']
```
This might be hard to handle, since it's difficult to distinguish between a wrapper not being able to do something and it trying and failing, but `"No registered toolkits can provide the capability"` is maybe not the right way to communicate this, since they have the general capability but fail on bad cases like this obtusely large molecule.

**Output**

**Comment by mattwthompson** [comment]
```python3
>>> from openff.toolkit.topology import Molecule
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
>>> from openff.toolkit.utils.toolkits import *
>>> mol = Molecule.from_smiles("F[U](F)(F)(F)(F)(F)")
>>> mol.generate_conformers(n_conformers=1)
Warning: OEMMFFParams::PrepMol() : unable to type atom 1 U
Warning: : Force field setup failed due to missing parameters
Warning: OEMMFFParams::PrepMol() : unable to type atom 1 U
Warning: : Force field setup failed due to missing parameters
[17:13:59] UFFTYPER: Unrecognized atom type: U_ (1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mwt/software/openforcefield/openff/toolkit/topology/molecule.py", line 3221, in generate_conformers
    return toolkit_registry.call(
  File "/Users/mwt/software/openforcefield/openff/toolkit/utils/toolkit_registry.py", line 380, in call
    raise ValueError(msg)
ValueError: No registered toolkits can provide the capability "generate_conformers" for args "(Molecule with name '' and SMILES 'F[U](F)(F)(F)(F)F',)" and kwargs "{'n_conformers': 1, 'rms_cutoff': None, 'clear_existing': True}"
Available toolkits are: [ToolkitWrapper around OpenEye Toolkit version 2021.1.1, ToolkitWrapper around The RDKit version 2021.03.5, ToolkitWrapper around AmberTools version 21.0, ToolkitWrapper around Built-in Toolkit version None]
 ToolkitWrapper around OpenEye Toolkit version 2021.1.1 <class 'openff.toolkit.utils.exceptions.ConformerGenerationError'> : OpenEye Omega conformer generation failed
 ToolkitWrapper around The RDKit version 2021.03.5 <class 'openff.toolkit.utils.exceptions.ConformerGenerationError'> : RDKit conformer generation failed.

>>> mol.generate_conformers(n_conformers=1, toolkit_registry=OpenEyeToolkitWrapper())
Warning: OEMMFFParams::PrepMol() : unable to type atom 1 U
Warning: : Force field setup failed due to missing parameters
Warning: OEMMFFParams::PrepMol() : unable to type atom 1 U
Warning: : Force field setup failed due to missing parameters
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mwt/software/openforcefield/openff/toolkit/topology/molecule.py", line 3231, in generate_conformers
    return toolkit.generate_conformers(
  File "/Users/mwt/software/openforcefield/openff/toolkit/utils/openeye_wrapper.py", line 1693, in generate_conformers
    raise ConformerGenerationError(
openff.toolkit.utils.exceptions.ConformerGenerationError: OpenEye Omega conformer generation failed
>>> mol.generate_conformers(n_conformers=1, toolkit_registry=RDKitToolkitWrapper())
[17:14:13] UFFTYPER: Unrecognized atom type: U_ (1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mwt/software/openforcefield/openff/toolkit/topology/molecule.py", line 3231, in generate_conformers
    return toolkit.generate_conformers(
  File "/Users/mwt/software/openforcefield/openff/toolkit/utils/rdkit_wrapper.py", line 894, in generate_conformers
    raise ConformerGenerationError("RDKit conformer generation failed.")
openff.toolkit.utils.exceptions.ConformerGenerationError: RDKit conformer generation failed.
>>> mol.generate_conformers(n_conformers=1, toolkit_registry=AmberToolsToolkitWrapper())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mwt/software/openforcefield/openff/toolkit/topology/molecule.py", line 3231, in generate_conformers
    return toolkit.generate_conformers(
AttributeError: 'AmberToolsToolkitWrapper' object has no attribute 'generate_conformers'
```

Over the course of #1050, I implemented everything I was originally confused about not having, so I'm going to close this.
