### ISSUE TITLE
Molecule.__repr__ gives confusing exception on bad molecules

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openff-toolkit#1073]
[`Molecule.__repr__`](https://github.com/openforcefield/openff-toolkit/blob/e4b56abcd7c688406ee7930dbd983a5eb758d231/openff/toolkit/topology/molecule.py#L2600-L2605) converts the molecule object to a SMILES, which can fail if the molecule is in a bogus state. For example, while jumping through hoops on something not directly related to this problem, I got exceptions about OpenEye failing to convert the molecule to SMILES despite not really doing anything with OpenEye.

```
>>> Molecule.from_rdkit(Chem.MolFromPDBFile("ala_ala.pdb", removeHs=False), allow_undefined_stereo=True, hydrogens_are_explicit=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mwt/software/openforcefield/openff/toolkit/topology/molecule.py", line 2603, in __repr__
    self.name, self.to_smiles()
  File "/Users/mwt/software/openforcefield/openff/toolkit/topology/molecule.py", line 2730, in to_smiles
    smiles = to_smiles_method(self, isomeric, explicit_hydrogens, mapped)
  File "/Users/mwt/software/openforcefield/openff/toolkit/utils/openeye_wrapper.py", line 1317, in to_smiles
    oemol = self.to_openeye(molecule)
  File "/Users/mwt/software/openforcefield/openff/toolkit/utils/openeye_wrapper.py", line 1179, in to_openeye
    raise Exception(
Exception: Programming error: OpenEye atom stereochemistry assumptions failed.
>>> mol = Molecule.from_rdkit(Chem.MolFromPDBFile("ala_ala.pdb", removeHs=False), allow_undefined_stereo=True, hydrogens_are_explicit=True)
>>> mol
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mwt/software/openforcefield/openff/toolkit/topology/molecule.py", line 2603, in __repr__
    self.name, self.to_smiles()
  File "/Users/mwt/software/openforcefield/openff/toolkit/topology/molecule.py", line 2730, in to_smiles
    smiles = to_smiles_method(self, isomeric, explicit_hydrogens, mapped)
  File "/Users/mwt/software/openforcefield/openff/toolkit/utils/openeye_wrapper.py", line 1317, in to_smiles
    oemol = self.to_openeye(molecule)
  File "/Users/mwt/software/openforcefield/openff/toolkit/utils/openeye_wrapper.py", line 1179, in to_openeye
    raise Exception(
Exception: Programming error: OpenEye atom stereochemistry assumptions failed.
```

This was confusing since I wasn't intentionally using OpenEye toolkits for anything, but is the first toolkit tried in `to_smiles()`.

Since this only happens in the `__repr__`, it won't actually prevent a "bad" molecule from being saved somewhere. It just results in a confusing user experience in an interpreter. I'm not sure it's bad, since it's a matter of storing a potentially bogus molecule, but the way it's communicated out is strange.

There are also subtle differences if RDKit and OpenEye disagree on if a molecule can be safely converted to SMILES:

```
>>> mol.to_smiles()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mwt/software/openforcefield/openff/toolkit/topology/molecule.py", line 2730, in to_smiles
    smiles = to_smiles_method(self, isomeric, explicit_hydrogens, mapped)
  File "/Users/mwt/software/openforcefield/openff/toolkit/utils/openeye_wrapper.py", line 1317, in to_smiles
    oemol = self.to_openeye(molecule)
  File "/Users/mwt/software/openforcefield/openff/toolkit/utils/openeye_wrapper.py", line 1179, in to_openeye
    raise Exception(
Exception: Programming error: OpenEye atom stereochemistry assumptions failed.
>>> mol.to_smiles(toolkit_registry=RDKitToolkitWrapper())
'[H][N]([C](=[O])[C@]([H])([N]([H])[C](=[O])[C@@]([H])([N]([H])[C]([O])[C]([H])([H])[H])[C]([H])([H])[H])[C]([H])([H])[H])[C]([H])([H])[H]'
```

**Describe the solution you'd like**
Either
1. Catch `to_smiles()` failures with a more descriptive exception, or
2. Throw it away and return something like `Molecule with name '' and bad SMILES` instead of fatally erroring out.

**Comment by j-wags** [comment]
Thanks @mattwthompson -- I like the second option, maybe in the case that it can't do the SMILES it could say `Molecule with name '' and bad SMILES and hill formula C8H1.`
