### ISSUE TITLE
`ForceField(..., disable_version_check)` behaves opposite of expected

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openff-toolkit#1315]
**Describe the bug**

The `disable_version_check` argument to the `ForceField` constructor behaves opposite of what I expect. Setting it to `True` appears to enable a version check whereas setting it to `False` disables the version check.

**To Reproduce**

Using (note `<SMIRNOFF version="99.3"`):
```
<?xml version="1.0" encoding='ASCII'?>
<SMIRNOFF version="99.3" aromaticity_model="OEAroModel_MDL">
  <vdW version="0.3" potential="Lennard-Jones-12-6" combining_rules="Lorentz-Berthelot" scale12="0.0" scale13="0.0" scale14="0.5" scale15="1" switch_width="1.0 * angstroms" cutoff="9.0 * angstroms" method="cutoff">
    <Atom smirks="[*:1]" id="n1" sigma="0.1* nanometers" epsilon="0.5* kilojoules_per_mole" />
  </vdW>
  <Electrostatics version="0.4" periodic_potential="Ewald3D-ConductingBoundary" nonperiodic_potential="Coulomb" exception_potential="Coulomb" scale12="0.0" scale13="0.0" scale14="0.833333" scale15="1.0"/>
  <ChargeIncrementModel version="0.4" number_of_conformers="1" partial_charge_method="zeros">
  </ChargeIncrementModel>
</SMIRNOFF>
```

`disable_version_check=False` disables the version check, yet `disable_version_check=True` _enables_ the version check.
```python3
>>> from openff.toolkit import *
>>> ForceField("unsupported_smirnoff_version.offxml",disable_version_check=False)  # The default value ...
<openff.toolkit.typing.engines.smirnoff.forcefield.ForceField object at 0x10b448760>
>>> ForceField("unsupported_smirnoff_version.offxml",disable_version_check=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mattthompson/software/openff-toolkit/openff/toolkit/typing/engines/smirnoff/forcefield.py", line 307, in __init__
    self.parse_sources(sources, allow_cosmetic_attributes=allow_cosmetic_attributes)
  File "/Users/mattthompson/software/openff-toolkit/openff/toolkit/typing/engines/smirnoff/forcefield.py", line 854, in parse_sources
    self._load_smirnoff_data(
  File "/Users/mattthompson/software/openff-toolkit/openff/toolkit/typing/engines/smirnoff/forcefield.py", line 923, in _load_smirnoff_data
    self._check_smirnoff_version_compatibility(str(version))
  File "/Users/mattthompson/software/openff-toolkit/openff/toolkit/typing/engines/smirnoff/forcefield.py", line 360, in _check_smirnoff_version_compatibility
    raise SMIRNOFFVersionError(
openff.toolkit.utils.exceptions.SMIRNOFFVersionError: SMIRNOFF offxml file was written with version 99.3, but this version of ForceField only supports version 0.1 to version 0.3
>>>
```

The error appears to stem from [this](https://github.com/openforcefield/openff-toolkit/blob/79a6fd25961f6d2f7959be02f4bb0933945f262e/openff/toolkit/typing/engines/smirnoff/forcefield.py#L352-L353) logic, which reads to my eye at the moment as backwards.

This behavior is not explicitly covered in tests and pretty unlikely to be an issue in the wild unless somebody manually creates a file like I did.

**Comment by mattwthompson** [comment]
After #1316 this now behaves as I expect:

```python3
>>> from openff.toolkit import ForceField
>>> ForceField("unsupported_smirnoff_version.offxml", disable_version_check=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mattthompson/software/openff-toolkit/openff/toolkit/typing/engines/smirnoff/forcefield.py", line 307, in __init__
    self.parse_sources(sources, allow_cosmetic_attributes=allow_cosmetic_attributes)
  File "/Users/mattthompson/software/openff-toolkit/openff/toolkit/typing/engines/smirnoff/forcefield.py", line 768, in parse_sources
    self._load_smirnoff_data(
  File "/Users/mattthompson/software/openff-toolkit/openff/toolkit/typing/engines/smirnoff/forcefield.py", line 837, in _load_smirnoff_data
    self._check_smirnoff_version_compatibility(str(version))
  File "/Users/mattthompson/software/openff-toolkit/openff/toolkit/typing/engines/smirnoff/forcefield.py", line 360, in _check_smirnoff_version_compatibility
    raise SMIRNOFFVersionError(
openff.toolkit.utils.exceptions.SMIRNOFFVersionError: SMIRNOFF offxml file was written with version 99.3, but this version of ForceField only supports version 0.1 to version 0.3
>>> ForceField("unsupported_smirnoff_version.offxml", disable_version_check=True)
<openff.toolkit.typing.engines.smirnoff.forcefield.ForceField object at 0x17934ea30>
```

Note that this bug concerns the **high-level** SMIRNOFF version, not the version of each section. For example, with this snippet:

```
<?xml version="1.0" encoding='ASCII'?>
<SMIRNOFF version="0.3" aromaticity_model="OEAroModel_MDL">
  <ChargeIncrementModel version="0.4" number_of_conformers="1" partial_charge_method="AM1-Mulliken">
  </ChargeIncrementModel>
</SMIRNOFF>
```

the version that's relevant in the `ForceField` constructor is `<SMIRNOFF version="0.3" ...`, not `<ChargeIncrementModel version="0.4" ...` or the version of any other section. There are, however, some tests concerned with version-checking individual sections. But as far as I'm aware, nobody's intentionally made a force field with a SMIRNOFF version greater than 0.3, so nobody's really run into this yet.
