### ISSUE TITLE
Molecule.enumerate_stereoisomers fails on some molecules with OpenEye toolkit backend

### ISSUE THREAD

**Issue by jchodera** [openforcefield/openff-toolkit#1364]
**Describe the bug**
`Molecule.enumerate_stereoisomers()` fails on some molecules with the OpenEye toolkit backend.

**To Reproduce**
Here is an example:
```python
>>> from openff.toolkit.topology import Molecule
>>> mol = Molecule.from_smiles('C1CN2C3CC4CC(C3)CC(C4)C2=N1', allow_unspecified_stereo=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: FrozenMolecule.from_smiles() got an unexpected keyword argument 'allow_unspecified_stereo'
>>> mol = Molecule.from_smiles('C1CN2C3CC4CC(C3)CC(C4)C2=N1', allow_undefined_stereo=True)
Warning (not error because allow_undefined_stereo=True): OEMol has unspecified stereochemistry. oemol.GetTitle(): 
Problematic atoms are:
Atom atomic num: 6, name: , idx: 5, aromatic: False, chiral: True with bonds:
bond order: 1, chiral: False to atom atomic num: 6, name: , idx: 4, aromatic: False, chiral: False
bond order: 1, chiral: False to atom atomic num: 6, name: , idx: 11, aromatic: False, chiral: False
bond order: 1, chiral: False to atom atomic num: 6, name: , idx: 6, aromatic: False, chiral: False
bond order: 1, chiral: False to atom atomic num: 1, name: , idx: 21, aromatic: False, chiral: False
Atom atomic num: 6, name: , idx: 7, aromatic: False, chiral: True with bonds:
bond order: 1, chiral: False to atom atomic num: 6, name: , idx: 6, aromatic: False, chiral: False
bond order: 1, chiral: False to atom atomic num: 6, name: , idx: 8, aromatic: False, chiral: False
bond order: 1, chiral: False to atom atomic num: 6, name: , idx: 9, aromatic: False, chiral: False
bond order: 1, chiral: False to atom atomic num: 1, name: , idx: 24, aromatic: False, chiral: False

>>> stereoisomers = mol.enumerate_stereoisomers()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lila/home/chodera/miniconda/envs/openeye/lib/python3.10/site-packages/openff/toolkit/topology/molecule.py", line 4920, in enumerate_stereoisomers
    molecules = toolkit_registry.call(
  File "/lila/home/chodera/miniconda/envs/openeye/lib/python3.10/site-packages/openff/toolkit/utils/toolkit_registry.py", line 366, in call
    raise e
  File "/lila/home/chodera/miniconda/envs/openeye/lib/python3.10/site-packages/openff/toolkit/utils/toolkit_registry.py", line 362, in call
    return method(*args, **kwargs)
  File "/lila/home/chodera/miniconda/envs/openeye/lib/python3.10/site-packages/openff/toolkit/utils/openeye_wrapper.py", line 662, in enumerate_stereoisomers
    isomol = self.from_openeye(mol, _cls=molecule.__class__)
  File "/lila/home/chodera/miniconda/envs/openeye/lib/python3.10/site-packages/openff/toolkit/utils/openeye_wrapper.py", line 950, in from_openeye
    raise UndefinedStereochemistryError(msg)
openff.toolkit.utils.exceptions.UndefinedStereochemistryError: Unable to make OFFMol from OEMol: OEMol has unspecified stereochemistry. oemol.GetTitle(): 
Problematic atoms are:
Atom atomic num: 6, name: , idx: 5, aromatic: False, chiral: True with bonds:
bond order: 1, chiral: False to atom atomic num: 6, name: , idx: 4, aromatic: False, chiral: False
bond order: 1, chiral: False to atom atomic num: 6, name: , idx: 11, aromatic: False, chiral: False
bond order: 1, chiral: False to atom atomic num: 6, name: , idx: 6, aromatic: False, chiral: False
bond order: 1, chiral: False to atom atomic num: 1, name: , idx: 21, aromatic: False, chiral: False
Atom atomic num: 6, name: , idx: 7, aromatic: False, chiral: True with bonds:
bond order: 1, chiral: False to atom atomic num: 6, name: , idx: 6, aromatic: False, chiral: False
bond order: 1, chiral: False to atom atomic num: 6, name: , idx: 8, aromatic: False, chiral: False
bond order: 1, chiral: False to atom atomic num: 6, name: , idx: 9, aromatic: False, chiral: False
bond order: 1, chiral: False to atom atomic num: 1, name: , idx: 24, aromatic: False, chiral: False
```
The molecule looks to be something like a substituted adamantane:
![image](https://user-images.githubusercontent.com/3656088/183276961-127ae529-bf03-400e-b6f6-49127ba1b0cb.png)

**Output**
(see example above)

**Computing environment (please complete the following information):**
```bash
$ uname -r
3.10.0-1160.45.1.el7.x86_64
```

<details>

<summary>output of `conda list`</summary>
```bash
$ conda list
# packages in environment at /lila/home/chodera/miniconda/envs/openeye:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
amberlite                 22.0                     pypi_0    pypi
ambertools                22.0            py310hfade12a_1    conda-forge
amberutils                21.0                     pypi_0    pypi
arpack                    3.7.0                hdefa2d7_2    conda-forge
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
attrs                     22.1.0             pyh71513ae_1    conda-forge
blas                      1.1                    openblas    conda-forge
blosc                     1.21.1               h83bc5f7_3    conda-forge
boost                     1.74.0          py310h7c3ba0c_5    conda-forge
boost-cpp                 1.74.0               h75c5d50_8    conda-forge
brotli                    1.0.9                h166bdaf_7    conda-forge
brotli-bin                1.0.9                h166bdaf_7    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.07.19           h06a4308_0  
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cairo                     1.16.0            ha61ee94_1011    conda-forge
certifi                   2022.6.15                pypi_0    pypi
commonmark                0.9.1                      py_0    conda-forge
cudatoolkit               10.2.89             h713d32c_10    conda-forge
curl                      7.84.0               h5eee18b_0  
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cython                    0.29.32                  pypi_0    pypi
dataclasses               0.8                pyhc8e2a94_3    conda-forge
expat                     2.4.8                h27087fc_0    conda-forge
fftw                      3.3.10          nompi_h77c792f_102    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.0               h8e229c2_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.34.4                   pypi_0    pypi
freetype                  2.11.0               h70c0345_0  
future                    0.18.2                   pypi_0    pypi
gettext                   0.21.0               hf68c758_0  
giflib                    5.2.1                h516909a_2    conda-forge
greenlet                  1.1.2                    pypi_0    pypi
h5py                      3.7.0                    pypi_0    pypi
hdf4                      4.2.15               h10796ff_3    conda-forge
hdf5                      1.12.1          nompi_h2386368_104    conda-forge
icu                       70.1                 h27087fc_0    conda-forge
importlib-metadata        4.11.4                   pypi_0    pypi
iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
jpeg                      9e                   h166bdaf_2    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.4                    pypi_0    pypi
krb5                      1.19.3               h3790be6_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libblas                   3.9.0           15_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h166bdaf_7    conda-forge
libbrotlidec              1.0.9                h166bdaf_7    conda-forge
libbrotlienc              1.0.9                h166bdaf_7    conda-forge
libcblas                  3.9.0           15_linux64_openblas    conda-forge
libcurl                   7.84.0               h91b91d3_0  
libdeflate                1.13                 h166bdaf_0    conda-forge
libedit                   3.1.20210910         h7f8727e_0  
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgfortran-ng            12.1.0              h69a702a_16    conda-forge
libgfortran5              12.1.0              hdcd56e2_16    conda-forge
libglib                   2.72.1               h2d90d5f_0    conda-forge
libgomp                   12.1.0              h8d9b700_16    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0           15_linux64_openblas    conda-forge
libnetcdf                 4.8.1           nompi_h329d8a1_102    conda-forge
libnghttp2                1.47.0               h727a467_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.20          pthreads_h78a6416_1    conda-forge
libpng                    1.6.37               h753d276_3    conda-forge
libssh2                   1.10.0               ha56f1ee_2    conda-forge
libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
libtiff                   4.4.0                h0e0dad5_3    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp                   1.2.3                h522a892_1    conda-forge
libwebp-base              1.2.3                h166bdaf_2    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxml2                   2.9.14               h22db469_3    conda-forge
libzip                    1.9.2                hc869a4a_0    conda-forge
libzlib                   1.2.12               h166bdaf_2    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
matplotlib                3.5.2                    pypi_0    pypi
matplotlib-base           3.5.2           py310h5701ce4_1    conda-forge
mdtraj                    1.9.7                    pypi_0    pypi
mmpbsa-py                 16.0                     pypi_0    pypi
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
netcdf-fortran            4.5.4           nompi_h2b6e579_100    conda-forge
networkx                  2.8.5              pyhd8ed1ab_0    conda-forge
nomkl                     3.0                           0  
numexpr                   2.8.3                    pypi_0    pypi
numpy                     1.23.1                   pypi_0    pypi
ocl-icd                   2.3.1                h7f98852_0    conda-forge
ocl-icd-system            1.0.0                         1    conda-forge
openblas                  0.3.20          pthreads_h320a7e8_1    conda-forge
openeye-toolkits          2022.1.1                py310_0    openeye
openeye-toolkits-python3-linux-x64 2022.1.1                 pypi_0    pypi
openff-forcefields        2.0.0              pyh6c4a22f_0    conda-forge
openff-toolkit            0.10.6             pyhd8ed1ab_0    conda-forge
openff-toolkit-base       0.10.6             pyhd8ed1ab_0    conda-forge
openjpeg                  2.4.0                hb52868f_1    conda-forge
openmm                    7.7.0                    pypi_0    pypi
openssl                   1.1.1q               h166bdaf_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
packmol                   20.010               h86c2bf4_0    conda-forge
packmol-memgen            1.2.3rc0                 pypi_0    pypi
pandas                    1.4.3                    pypi_0    pypi
parmed                    3.4.3                    pypi_0    pypi
pcre                      8.45                 h9c3ff4c_0    conda-forge
pdb4amber                 22.0                     pypi_0    pypi
perl                      5.32.1          2_h7f98852_perl5    conda-forge
pillow                    9.2.0                    pypi_0    pypi
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
pluggy                    1.0.0                    pypi_0    pypi
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
py                        1.11.0             pyh6c4a22f_0    conda-forge
pycairo                   1.21.0                   pypi_0    pypi
pygments                  2.12.0             pyhd8ed1ab_0    conda-forge
pymsmt                    22.0                     pypi_0    pypi
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pytables                  3.7.0           py310hf5df6ce_0    conda-forge
pytest                    7.1.2                    pypi_0    pypi
python                    3.10.5          h582c2e5_0_cpython    conda-forge
python-constraint         1.4.0                      py_0    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pytraj                    2.0.6                    pypi_0    pypi
pytz                      2022.1             pyhd8ed1ab_0    conda-forge
rdkit                     2022.03.4       py310h1c297d8_0    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
reportlab                 3.5.68                   pypi_0    pypi
rich                      12.5.1             pyhd8ed1ab_0    conda-forge
sander                    22.0                     pypi_0    pypi
scipy                     1.9.0                    pypi_0    pypi
setuptools                63.4.1                   pypi_0    pypi
six                       1.16.0             pyh6c4a22f_0    conda-forge
smirnoff99frosst          1.1.0              pyh44b312d_0    conda-forge
snappy                    1.1.9                hbd366e4_1    conda-forge
sqlalchemy                1.4.39                   pypi_0    pypi
sqlite                    3.39.2               h4ff8645_0    conda-forge
tables                    3.7.0                    pypi_0    pypi
tk                        8.6.12               h27826a3_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
typing-extensions         4.3.0                hd8ed1ab_0    conda-forge
typing_extensions         4.3.0              pyha770c72_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
unicodedata2              14.0.0                   pypi_0    pypi
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xmltodict                 0.13.0             pyhd8ed1ab_0    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-libxt                1.2.1                h7f98852_2    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zipp                      3.8.1              pyhd8ed1ab_0    conda-forge
zlib                      1.2.12               h166bdaf_2    conda-forge
zstd                      1.5.2                h8a70e8d_2    conda-forge
```
</details>

 - Output of running `conda list`

**Comment by jchodera** [comment]
Here are a bunch more examples that fail in exactly the same way:
```
C1CN2C3CC4CC(C3)CC(C4)C2=N1
CC12CC3CC(C1)(CC(C3)(C2)N/C(=N/c4ccccc4I)/N)C
CS(=O)c1ccc(cc1)C2CN3CCCC3c4c2cccc4
C1CCN2CCc3c(nc(s3)N)C2C1
CC(CSC(=O)C)C(=O)N(CC(=O)O)C1CC2CCC1C2
CN([C@H]1CCN2CCc3c4ccccc4oc3[C@H]2C1)S(=O)(=O)CCO
Cc1cc2c(n1C)CCCC23C(=O)NC(=O)N3
c1cc2c(cc1Cl)C3(CCS2)C(=O)N=C(O3)O
CN1C2CCC1C(C(C2)c3ccc(cc3)I)C(=O)N4CCCO4
COc1cc2c(cc1Br)C3(CC(=O)NC3=O)C(=O)N(C2=O)Cc4ccc(cc4F)Br
CC12CCC(C(C1)(Cc3c2cc(cc3)O)COC)N(C)C
CN1C2CCC1CC(C2)N3CCN(C3=O)c4cc(ccc4OC)Cl
c1cc(ccc1C(c2ccc(cc2)F)OC3CC4CCC(C3)N4C=O)F
c1cc2n(c1)C3(CC(=O)NC3=O)C(=O)N(C2=O)Cc4ccc(cc4)N
Cc1cc2c([nH]1)ccc3c2CN4CCc5cc(c(cc5C4O3)OC)OC
Cn1c2c(c(=O)n(c1=O)C)nn(n2)C3CC4CCC3C4
c1cc(oc1)C(=O)CCCN2C3CCC2c4c5cc(ccc5[nH]c4C3)F
CC(=O)OC1C[N+]2(Cc3cc4c(cc3C15C2CC(C=C5)OC)OCO4)C
Cc1cc(c2c(c1)O[C@]34[C@@H](C(CC=C3C2=O)N(C4=O)C)O)O
c1cc(ccc1[C@H]2C[C@H]3CCC4C2C(=O)CN34)F
CC1(C2CCC1(C(=O)C2)CS(=O)(=O)NC(=N)N)C
CCC[C@H]1CC[C@H]2N1[C@@H](CC2)CCCCCC(=O)C
C1CN2CCC1C3(C2)COC(=O)N3
CN(C)CCOc1cc(cc(c1F)F)N2CC3CC(C2)CNC3
CC(C)(C)OC(=O)N[C@@H]1CC[C@]2(CCCN2C1)C(=O)OC
c1c(onc1C#N)CO/N=C/2\C[NH+]3CCC2C3
c1cc(ccc1NC(=O)[C@@H]2C3CC(C2C(=O)O)C=C3)S(=O)(=O)Nc4nnc(s4)S(=O)(=O)N
CC(=O)NCC1C2CCC3N2C/C(=C\c4cccs4)/C1C3
CN1CCN2c3c(cccc3OS(=O)(=O)C(F)(F)F)Cc4ccccc4C2C1
CC1=CC2Cc3c(ccc(=O)[nH]3)C4(C1)C2CCC[NH+]4C
COc1ccccc1[C@@H]2CC3(CCCNC3c4ccccc4)OC2
CCOC(=O)C1CN2CC(C1=O)CCC2CN(C)C
CC[C@]12CCN(C([C@@H]1C)C(=O)c3c2cc(cc3)NC=O)CC4CC4
```
