### ISSUE TITLE
Saturated Planner nitrogen

### ISSUE THREAD

**Issue by xiki-tempula** [openforcefield/openff-toolkit#1547]
**Describe the bug**
I had a ligand 
[ligand_12t.sdf.zip](https://github.com/openforcefield/openff-toolkit/files/10731178/ligand_12t.sdf.zip)
, which contains a planner saturated nitrogen. If I pass this molecule into openff-tookit, it will complain this planner nitrogen being chiral and has no stereochemistry.

**To Reproduce**
```
from openeye import oechem
from openff.toolkit.topology import Molecule as OpenFFMol
ifs = oechem.oemolistream()
if ifs.open('ligand_12t.sdf'):
	for mol in ifs.GetOEGraphMols():
		openffmol = OpenFFMol.from_openeye(mol)
```

**Output**
```
Traceback (most recent call last):
  File "/Users/zwu/mambaforge/envs/BSSOrion/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3442, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-a7df804a7ba1>", line 3, in <module>
    openffmol = OpenFFMol.from_openeye(mol)
  File "/Users/zwu/mambaforge/envs/BSSOrion/lib/python3.8/site-packages/openff/toolkit/utils/base_wrapper.py", line 52, in wrapped_function
    value = func(*args, **kwargs)
  File "/Users/zwu/mambaforge/envs/BSSOrion/lib/python3.8/site-packages/openff/toolkit/topology/molecule.py", line 4265, in from_openeye
    molecule = toolkit.from_openeye(
  File "/Users/zwu/mambaforge/envs/BSSOrion/lib/python3.8/site-packages/openff/toolkit/utils/openeye_wrapper.py", line 1159, in from_openeye
    raise UndefinedStereochemistryError(msg)
openff.toolkit.utils.exceptions.UndefinedStereochemistryError: Unable to make OFFMol from OEMol: OEMol has unspecified stereochemistry. oemol.GetTitle(): ligand_12t
Problematic atoms are:
Atom atomic num: 7, name: , idx: 27, aromatic: False, chiral: True with bonds:
bond order: 1, chiral: False to atom atomic num: 6, name: , idx: 18, aromatic: False, chiral: False
bond order: 1, chiral: False to atom atomic num: 6, name: , idx: 16, aromatic: False, chiral: False
bond order: 1, chiral: False to atom atomic num: 6, name: , idx: 7, aromatic: True, chiral: False
```

**Computing environment (please complete the following information):**
 - Operating system: 
 - Output of running `conda list`

**Additional context**
The cause of this is that the nitrogen is characterised as chiral as it is saturated. However, it has no stereochemistry as it is planner.
I think the solution could be to change 

https://github.com/openforcefield/openff-toolkit/blob/main/openff/toolkit/utils/openeye_wrapper.py#L1124

To 

```
carbonOnly = True
oechem.OEPerceiveChiral(mol, carbonOnly)
```

Thus, only Chiral carbon will be recognised.

**Comment by j-wags** [comment]
Hi @xiki-tempula,

Thanks for the suggestion. This is another face of the horrible #146. The `carbonOnly` keyword is new to me, and could be a nice solution, though it would potentially lose track of hypervalent sulfur and phosphorous stereo.

In the interim, you should be able to circumvent that error by loading the molecule with the `allow_undefined_stereo=True` kwarg - Does that unblock your work?
