### ISSUE TITLE
OpenFF toolkit fails to generate charges for some molecules due to rdkit issues

### ISSUE THREAD

**Issue by mark-cresset** [openforcefield/openff-toolkit#1559]
**Describe the bug**
If you try to parameterise the molecule "[H][C]1=[N][C]2=[C]([C]([H])=[C]([H])[N]2[H])[N]2[C]1=[N][C]([H])=[C]2[C]12[C]([H])([H])[C]([C]([H])([H])[O][C]([H])([H])[H])([C]1([H])[H])[C]2([H])[H]" the charging step fails due to RDkit not generating conformations

**To Reproduce**
Create a PDB containing the above molecule, and run something like

```
import openmm.app as app
from openff.toolkit.topology import Molecule
pdb_file = app.PDBFile(r'/tmp/FieldEngine-mark/OpenMM_Force_Fields_2044640_1/input.pdb')
force_field = app.ForceField('amber/protein.ff14SB.xml', 'amber/DNA.OL15.xml', 'amber/RNA.OL3.xml')
ligand_smiles_file_dict = {r'[H][C]1=[N][C]2=[C]([C]([H])=[C]([H])[N]2[H])[N]2[C]1=[N][C]([H])=[C]2[C@]12[C]([H])([H])[C@]([C]([H])([H])[O][C]([H])([H])[H])([C]1([H])[H])[C]2([H])[H]' : '/tmp/FieldEngine-mark/OpenMM_Force_Fields_2044640_1/_MOL_47_46.sdf', }
molecules = []
for smiles, sdf_file in ligand_smiles_file_dict.items():
    try:
        molecule = Molecule.from_file(sdf_file)
    except:
        molecule = Molecule.from_smiles(smiles)
    molecules.append(molecule)
template_generator = SMIRNOFFTemplateGenerator(molecules=molecules, forcefield=r'openff_unconstrained-2.0.0.offxml')
force_field.registerTemplateGenerator(template_generator.generator)
modeller = app.Modeller(pdb_file.topology, pdb_file.positions)
modeller.addExtraParticles(force_field)

```

**Output**
```
Traceback (most recent call last):
  File "/tmp/FieldEngine-mark/OpenMM_Force_Fields_2044501_1/generate_simulation_files.py", line 79, in <module>
    modeller.addExtraParticles(force_field)
  File "/home/mark/.conan/data/OpenMM/8.0.0/cresset/stable/package/ba107ff23e2262f45993d21b4b16ca56bd0b5dfc/python/openmm/app/modeller.py", line 1100, in addExtraParticles
    templates = forcefield._matchAllResiduesToTemplates(ForceField._SystemData(self.topology), self.topology, {}, False, True, False)
  File "/home/mark/.conan/data/OpenMM/8.0.0/cresset/stable/package/ba107ff23e2262f45993d21b4b16ca56bd0b5dfc/python/openmm/app/forcefield.py", line 1423, in _matchAllResiduesToTemplates
    if generator(self, res):
  File "/home/mark/.conan/data/Flare-Python/9.11/cresset/stable/package/f90f414bcf9ce2f7c814d855f2dadd8618f6e256/lib/python3.9/site-packages/openmmforcefields/generators/template_generators.py", line 321, in generator
    ffxml_contents = self.generate_residue_template(molecule)
  File "/home/mark/.conan/data/Flare-Python/9.11/cresset/stable/package/f90f414bcf9ce2f7c814d855f2dadd8618f6e256/lib/python3.9/site-packages/openmmforcefields/generators/template_generators.py", line 1425, in generate_residue_template
    system = self._smirnoff_forcefield.create_openmm_system(molecule.to_topology(), charge_from_molecules=charge_from_molecules)
  File "/home/mark/.conan/data/Flare-Python/9.11/cresset/stable/package/f90f414bcf9ce2f7c814d855f2dadd8618f6e256/lib/python3.9/site-packages/openff/utilities/utilities.py", line 77, in wrapper
    return function(*args, **kwargs)
  File "/home/mark/.conan/data/Flare-Python/9.11/cresset/stable/package/f90f414bcf9ce2f7c814d855f2dadd8618f6e256/lib/python3.9/site-packages/openff/toolkit/typing/engines/smirnoff/forcefield.py", line 1120, in create_openmm_system
    interchange = self.create_interchange(
  File "/home/mark/.conan/data/Flare-Python/9.11/cresset/stable/package/f90f414bcf9ce2f7c814d855f2dadd8618f6e256/lib/python3.9/site-packages/openff/utilities/utilities.py", line 77, in wrapper
    return function(*args, **kwargs)
  File "/home/mark/.conan/data/Flare-Python/9.11/cresset/stable/package/f90f414bcf9ce2f7c814d855f2dadd8618f6e256/lib/python3.9/site-packages/openff/toolkit/typing/engines/smirnoff/forcefield.py", line 1194, in create_interchange
    return Interchange.from_smirnoff(
  File "/home/mark/.conan/data/Flare-Python/9.11/cresset/stable/package/f90f414bcf9ce2f7c814d855f2dadd8618f6e256/lib/python3.9/site-packages/openff/interchange/components/interchange.py", line 385, in from_smirnoff
    electrostatics_handler = SMIRNOFFElectrostaticsHandler._from_toolkit(
  File "/home/mark/.conan/data/Flare-Python/9.11/cresset/stable/package/f90f414bcf9ce2f7c814d855f2dadd8618f6e256/lib/python3.9/site-packages/openff/interchange/components/smirnoff.py", line 1109, in _from_toolkit
    handler.store_matches(
  File "/home/mark/.conan/data/Flare-Python/9.11/cresset/stable/package/f90f414bcf9ce2f7c814d855f2dadd8618f6e256/lib/python3.9/site-packages/openff/interchange/components/smirnoff.py", line 1577, in store_matches
    matches, potentials = self._find_reference_matches(
  File "/home/mark/.conan/data/Flare-Python/9.11/cresset/stable/package/f90f414bcf9ce2f7c814d855f2dadd8618f6e256/lib/python3.9/site-packages/openff/interchange/components/smirnoff.py", line 1430, in _find_reference_matches
    ) = cls._find_charge_model_matches(
  File "/home/mark/.conan/data/Flare-Python/9.11/cresset/stable/package/f90f414bcf9ce2f7c814d855f2dadd8618f6e256/lib/python3.9/site-packages/openff/interchange/components/smirnoff.py", line 1368, in _find_charge_model_matches
    partial_charges = cls._compute_partial_charges(
  File "/home/mark/.conan/data/Flare-Python/9.11/cresset/stable/package/f90f414bcf9ce2f7c814d855f2dadd8618f6e256/lib/python3.9/site-packages/openff/interchange/components/smirnoff.py", line 1194, in _compute_partial_charges
    molecule.assign_partial_charges(method)
  File "/home/mark/.conan/data/Flare-Python/9.11/cresset/stable/package/f90f414bcf9ce2f7c814d855f2dadd8618f6e256/lib/python3.9/site-packages/openff/toolkit/topology/molecule.py", line 2516, in assign_partial_charges
    toolkit_registry.call(
  File "/home/mark/.conan/data/Flare-Python/9.11/cresset/stable/package/f90f414bcf9ce2f7c814d855f2dadd8618f6e256/lib/python3.9/site-packages/openff/toolkit/utils/toolkit_registry.py", line 370, in call
    raise ValueError(msg)
ValueError: No registered toolkits can provide the capability "assign_partial_charges" for args "()" and kwargs "{'molecule': Molecule with name 'Untitled' and SMILES '[H][C]1=[N][C]2=[C]([C]([H])=[C]([H])[N]2[H])[N]2[C]1=[N][C]([H])=[C]2[C]12[C]([H])([H])[C]([C]([H])([H])[O][C]([H])([H])[H])([C]1([H])[H])[C]2([H])[H]', 'partial_charge_method': 'am1bcc', 'use_conformers': None, 'strict_n_conformers': False, 'normalize_partial_charges': True, '_cls': <class 'openff.toolkit.topology.molecule.Molecule'>}"
Available toolkits are: [ToolkitWrapper around The RDKit version 2022.09.3, ToolkitWrapper around AmberTools version 21.0, ToolkitWrapper around Built-in Toolkit version None]
 ToolkitWrapper around The RDKit version 2022.09.3 <class 'openff.toolkit.utils.exceptions.ChargeMethodUnavailableError'> : partial_charge_method 'am1bcc' is not available from RDKitToolkitWrapper. Available charge methods are ['mmff94']
 ToolkitWrapper around AmberTools version 21.0 <class 'openff.toolkit.utils.exceptions.ConformerGenerationError'> : RDKit conformer generation failed.
 ToolkitWrapper around Built-in Toolkit version None <class 'openff.toolkit.utils.exceptions.ChargeMethodUnavailableError'> : Partial charge method "am1bcc"" is not supported by the Built-in toolkit. Available charge methods are ['zeros', 'formal_charge']

```

**Computing environment (please complete the following information):**
Complicated - we run this as part of a Flare python environment, not in Conda.

**Additional context**
If I edit generate_conformers in rdkit_wrapper.py to take the molecule to and from SMILES, then the problem disappears:

```
rdmol = self.to_rdkit(molecule)
        # TODO: This generates way more conformations than omega, given the same
        # nConfs and RMS threshold. Is there some way to set an energy cutoff as well?
        from rdkit import Chem
        import sys

        print("DEBUG {}".format(Chem.MolToSmiles(rdmol)),file=sys.stderr)
        # THIS LINE FIXES THE PROBLEM
        rdmol=Chem.MolFromSmiles(Chem.MolToSmiles(rdmol))
        print("DEBUG 2 {}".format(Chem.MolToSmiles(rdmol)),file=sys.stderr)

        first_conformer_generation_status = AllChem.EmbedMultipleConfs(...

```
Just adding a SanitizeMol call doesn't fix the problem.

So, this looks to me like there's a subtle problem somewhere in the Molecule-to-rdkit conversion. If you can work out what that is, then that's the place to fix it (I couldn't see anything obvious).  Otherwise, it might be worth adding a second fallback to do a Molecule->SMILES->RDkit conversion if the first two EmbedMultipleConfs calls fail.

**Comment by mattwthompson** [comment]
I'm unable to reproduce this particular behavior; something is up with that SMILES pattern.

```python3
>>> from openff.toolkit import Molecule
>>> from openff.toolkit.utils.openeye_wrapper import OpenEyeToolkitWrapper
>>> from openff.toolkit.utils.rdkit_wrapper import RDKitToolkitWrapper
>>> SMILES = "[H][C]1=[N][C]2=C[N]2[C]1=[N]C=[C]2[C]12C([H])C([C]1([H])[H])[C]2([H])[H]"
>>> Molecule.from_smiles(SMILES, OpenEyeToolkitWrapper())
Warning: Problem parsing SMILES:
Warning: Unclosed ring.
Warning: [H][C]1=[N][C]2=C[N]2[C]1=[N]C=[C]2[C]12C([H])C([C]1([H])[H])[C]2([H])[H]
Warning:                                        ^

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mattthompson/software/openff-toolkit/openff/toolkit/topology/molecule.py", line 1807, in from_smiles
    molecule = toolkit_registry.call(
  File "/Users/mattthompson/software/openff-toolkit/openff/toolkit/utils/toolkit_registry.py", line 356, in call
    raise e
  File "/Users/mattthompson/software/openff-toolkit/openff/toolkit/utils/toolkit_registry.py", line 352, in call
    return method(*args, **kwargs)
  File "/Users/mattthompson/software/openff-toolkit/openff/toolkit/utils/openeye_wrapper.py", line 1984, in from_smiles
    raise SMILESParseError("Unable to parse the SMILES string")
openff.toolkit.utils.exceptions.SMILESParseError: Unable to parse the SMILES string
>>> Molecule.from_smiles(SMILES, OpenEyeToolkitWrappe
KeyboardInterrupt
>>> Molecule.from_smiles(SMILES, toolkit_registry=OpenEyeToolkitWrapper())
Warning: Problem parsing SMILES:
Warning: Unclosed ring.
Warning: [H][C]1=[N][C]2=C[N]2[C]1=[N]C=[C]2[C]12C([H])C([C]1([H])[H])[C]2([H])[H]
Warning:                                        ^

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mattthompson/software/openff-toolkit/openff/toolkit/topology/molecule.py", line 1816, in from_smiles
    molecule = toolkit.from_smiles(  # type: ignore[attr-defined]
  File "/Users/mattthompson/software/openff-toolkit/openff/toolkit/utils/openeye_wrapper.py", line 1984, in from_smiles
    raise SMILESParseError("Unable to parse the SMILES string")
openff.toolkit.utils.exceptions.SMILESParseError: Unable to parse the SMILES string
>>> Molecule.from_smiles(SMILES, toolkit_registry=RDKitToolkitWrapper())
[10:44:10] SMILES Parse Error: ring closure 2 duplicates bond between atom 9 and atom 10 for input: '[H][C]1=[N][C]2=C[N]2[C]1=[N]C=[C]2[C]12C([H])C([C]1([H])[H])[C]2([H])[H]'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mattthompson/software/openff-toolkit/openff/toolkit/topology/molecule.py", line 1816, in from_smiles
    molecule = toolkit.from_smiles(  # type: ignore[attr-defined]
  File "/Users/mattthompson/software/openff-toolkit/openff/toolkit/utils/rdkit_wrapper.py", line 991, in from_smiles
    raise SMILESParseError("Unable to parse the SMILES string")
openff.toolkit.utils.exceptions.SMILESParseError: Unable to parse the SMILES string
```

The failure I'm seeing pops up before sanitization steps:
```python
>>> from rdkit import Chem
>>> SMILES = "[H][C]1=[N][C]2=C[N]2[C]1=[N]C=[C]2[C]12C([H])C([C]1([H])[H])[C]2([H])[H]"
>>> Chem.MolFromSmiles(SMILES, sanitize=False) is None
[10:47:12] SMILES Parse Error: ring closure 2 duplicates bond between atom 9 and atom 10 for input: '[H][C]1=[N][C]2=C[N]2[C]1=[N]C=[C]2[C]12C([H])C([C]1([H])[H])[C]2([H])[H]'
True
```

It looks like your code is reading an SDF file instead of using that SMILES pattern - maybe that can be loaded into a sane state which can later go through (some) of the conversions that happen in conformer generation, partial charge assignment, etc. Are you able to share this SDF?

**Comment by pavankum** [comment]
@mattwthompson the error message has a different smiles which fails on rdkit conformer generation.
```
mol = Molecule.from_smiles("[H][C]1=[N][C]2=[C]([C]([H])=[C]([H])[N]2[H])[N]2[C]1=[N][C]([H])=[C]2[C@]12[C]([H])([H])[C@]([C]([H])([H])[O][C]([H])([H])[H])([C]1([H])[H])[C]2([H])[H]")
```
![image](https://user-images.githubusercontent.com/16142894/223181865-e50c8e19-440e-41e3-8775-8f35d5340c02.png)

**Comment by mark-cresset** [comment]
Apologies, I may have made a typo in the original bug report. The molecule as listed by Pavan above is the correct one.

**Comment by j-wags** [comment]
Thanks for the great report - This reproduces for me, and I'll be working on it. 

My current most interesting finding is that this works fine using just RDKit:

```python
from rdkit import Chem
from rdkit.Chem import AllChem
rdmol = Chem.MolFromSmiles("[H][C]1=[N][C]2=[C]([C]([H])=[C]([H])[N]2[H])[N]2[C]1=[N][C]([H])=[C]2[C@]12[C]([H])([H])[C@]([C]([H])([H])[O][C]([H])([H])[H])([C]1([H])[H])[C]2([H])[H]")
status = AllChem.EmbedMultipleConfs(
            rdmol,
            numConfs=10,
            pruneRmsThresh=1,
            randomSeed=1,
            # params=AllChem.ETKDG()
        )
print(status, not(status), rdmol.GetNumConformers())
```
> <rdkit.rdBase._vecti object at 0x186e707c0> False 2

But if I simply roundtrip the molecule through an OFFMol and then do the exact same thing, the conf gen fails:

```python
from openff.toolkit import Molecule
from rdkit import Chem
from rdkit.Chem import AllChem
rdmol = Chem.MolFromSmiles("[H][C]1=[N][C]2=[C]([C]([H])=[C]([H])[N]2[H])[N]2[C]1=[N][C]([H])=[C]2[C@]12[C]([H])([H])[C@]([C]([H])([H])[O][C]([H])([H])[H])([C]1([H])[H])[C]2([H])[H]")
rdmol = Molecule.from_rdkit(rdmol).to_rdkit()
status = AllChem.EmbedMultipleConfs(
            rdmol,
            numConfs=10,
            pruneRmsThresh=1,
            randomSeed=1,
            # params=AllChem.ETKDG()
        )
print(status, not(status), rdmol.GetNumConformers())
```
> <rdkit.rdBase._vecti object at 0x186f9cf40> True 0
