### ISSUE TITLE
ForceField.parse_sources fails when given a string

### ISSUE THREAD

**Issue by ntBre** [openforcefield/openff-toolkit#1803]
I was looking at the ForceField API in the toolkit today, and I think there might be a bug in `ForceField.parse_sources`. The docs say it should take as an argument `a string or file-like object or open file handle or URL`, but if you pass it a string, it tries to iterate over the characters of the string, reading files named by each character:

```python
from openff.toolkit import ForceField

ForceField("openff-2.1.0.offxml").parse_sources("openff-2.1.0.offxml")
```

Leads to this error:

```
Traceback (most recent call last):
  File "/tmp/try.py", line 3, in <module>
    ForceField("openff-2.1.0.offxml").parse_sources("openff-2.1.0.offxml")
  File "/home/brent/mambaforge/envs/coprelos/lib/python3.12/site-packages/openff/toolkit/typing/engines/smirnoff/forcefield.py", line 795, in parse_sources
    smirnoff_data = self.parse_smirnoff_from_source(source)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/brent/mambaforge/envs/coprelos/lib/python3.12/site-packages/openff/toolkit/typing/engines/smirnoff/forcefield.py", line 1054, in parse_smirnoff_from_source
    raise IOError(msg)
OSError: Source 'o' could not be read. If this is a file, ensure that the path is correct.
Looked in the following paths and found no files named 'o':
    /tmp
    /home/brent/mambaforge/envs/coprelos/lib/python3.12/site-packages/openff/amber_ff_ports/offxml
    /home/brent/mambaforge/envs/coprelos/lib/python3.12/site-packages/openforcefields/offxml
    /home/brent/mambaforge/envs/coprelos/lib/python3.12/site-packages/smirnoff99frosst/offxml
If 'o' is present as a file, ensure it is in a known SMIRNOFF encoding.
Valid formats are: ['XML']
Parsing failed while trying to parse source as a file with the following exception and message:
<class 'openff.toolkit.utils.exceptions.SMIRNOFFParseError'>
syntax error: line 1, column 0
```

If I pass it `["openff-2.1.0.offxml"]` instead, it seems to work. I'm not really sure what this method is supposed to be used for, but it looks like something is wrong.

https://github.com/openforcefield/openff-toolkit/blob/1c1146a67d1773d06ee64fe221d7f0d118952b4f/openff/toolkit/typing/engines/smirnoff/forcefield.py#L765

**Comment by j-wags** [comment]
Resolved by #1804
