### ISSUE TITLE
OE wrapper failing conformer generation when molecule is created using `from_openeye` but not when using `Molecule.from_file`

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openff-toolkit#1962]
**Describe the bug**

**To Reproduce**

```python
from openeye import oechem
from openff.toolkit.topology import Molecule as OpenFFMol
ifs = oechem.oemolistream("failed_conformer_generation.sdf")
(oemol,) = [oechem.OEMol(mol) for mol in ifs.GetOEMols()]
openffmol = OpenFFMol.from_openeye(oemol)
openffmol.assign_partial_charges("am1bccelf10")
```

outputs

```
Warning: : Failed to build structure from CT
Warning: : Failed to build structure from CT
Traceback (most recent call last):
  File "/Users/jeffreywagner/projects/OpenForceField/2024_11_08_zhiyi_from_oe_bug/test.py", line 12, in <module>
    openffmol.assign_partial_charges("am1bccelf10")
  File "/Users/jeffreywagner/projects/OpenForceField/openff-toolkit/openff/toolkit/topology/molecule.py", line 2675, in assign_partial_charges
    toolkit_registry.call(
  File "/Users/jeffreywagner/projects/OpenForceField/openff-toolkit/openff/toolkit/utils/toolkit_registry.py", line 280, in call
    raise ValueError(msg)
ValueError: No registered toolkits can provide the capability "assign_partial_charges" for args "()" and kwargs "{'molecule': Molecule with name 'docked_RECEPTOR' and SMILES '[H][C@@]12C(C([C@]([N+]1([H])[H])(C(N(C2([H])[H])[H])([H])[H])[H])([H])[H])([H])[H]', 'partial_charge_method': 'am1bccelf10', 'use_conformers': None, 'strict_n_conformers': False, 'normalize_partial_charges': True, '_cls': <class 'openff.toolkit.topology.molecule.Molecule'>}"
Available toolkits are: [ToolkitWrapper around OpenEye Toolkit version 2024.1.0, ToolkitWrapper around The RDKit version 2024.03.5, ToolkitWrapper around AmberTools version 23.6, ToolkitWrapper around Built-in Toolkit version None]
 ToolkitWrapper around OpenEye Toolkit version 2024.1.0 <class 'openff.toolkit.utils.exceptions.ConformerGenerationError'> : OpenEye Omega conformer generation failed
 ToolkitWrapper around The RDKit version 2024.03.5 <class 'openff.toolkit.utils.exceptions.ChargeMethodUnavailableError'> : partial_charge_method 'am1bccelf10' is not available from RDKitToolkitWrapper. Available charge methods are {'mmff94': {}, 'gasteiger': {}}
 ToolkitWrapper around AmberTools version 23.6 <class 'openff.toolkit.utils.exceptions.ChargeMethodUnavailableError'> : partial_charge_method 'am1bccelf10' is not available from AmberToolsToolkitWrapper. Available charge methods are {'am1bcc': {'antechamber_keyword': 'bcc', 'min_confs': 1, 'max_confs': 1, 'rec_confs': 1}, 'am1-mulliken': {'antechamber_keyword': 'mul', 'min_confs': 1, 'max_confs': 1, 'rec_confs': 1}, 'gasteiger': {'antechamber_keyword': 'gas', 'min_confs': 0, 'max_confs': 0, 'rec_confs': 0}}
 ToolkitWrapper around Built-in Toolkit version None <class 'openff.toolkit.utils.exceptions.ChargeMethodUnavailableError'> : Partial charge method "am1bccelf10"" is not supported by the Built-in toolkit. Available charge methods are {'zeros': {'rec_confs': 0, 'min_confs': 0, 'max_confs': 0}, 'formal_charge': {'rec_confs': 0, 'min_confs': 0, 'max_confs': 0}}
```

However using the OpenEye wrapper to load the file directly there is no issue:

```python
openffmol = OpenFFMol.from_file("ligand.sdf")
openffmol.assign_partial_charges("am1bccelf10")
```

> (no errors)

**Computing environment (please complete the following information):**
 - Operating system: MacOS 15.0.1, M1 macbook air
 - `openff-toolkit-base       0.16.6             pyhd8ed1ab_0    conda-forge`
 - This reproduces on at least openeye-toolkits 2024, 2023, and 2022

**Comment by j-wags** [comment]
Adding a call to `oechem.OE3DToInternalStereo(oemol)` fixes this. It it possible that the stereo in the connectivity table contradicts what's in 3d? With the bridged ring in this mol that could make sense as being an issue, since the wrong stereochemistry could make the geometry impossible. 

```python
from openeye import oechem
from openff.toolkit.topology import Molecule as OpenFFMol
ifs = oechem.oemolistream("failed_conformer_generation.sdf")
(oemol,) = [oechem.OEMol(mol) for mol in ifs.GetOEMols()]
oechem.OE3DToInternalStereo(oemol)
openffmol = OpenFFMol.from_openeye(oemol)
openffmol.assign_partial_charges("am1bccelf10")
```

**Comment by j-wags** [comment]
I think the stereo is marked wrong in the input file. I've highlighted the carbon atoms in question here:

<img width="772" alt="Screenshot 2024-11-11 at 11 58 08 AM" src="https://github.com/user-attachments/assets/d233b5e5-0d96-49a9-b4bb-f67b2ba80258">

The `1`s in the middle column indicate stereo "parity" (basically clockwise/counterclockwise orientation relative to the index of the atoms in the file, see appendix A [here](https://discover.3ds.com/sites/default/files/2020-08/biovia_ctfileformats_2020.pdf)). Ignoring the specific meaning of "1" here, visually it looks like the carbons in question should have opposite parity - one goes clockwise and the other counterclockwise. Visually we can see this by drawing an arrow in the direction of increasing atom indices around each stereogenic carbon (carbon 6 goes counterclockwise through atoms 2-4-9 with hydrogen 14 going back, and carbon 7 goes clockwise through 3-5-9 with hydrogen 19 going back):

<img width="335" alt="Screenshot 2024-11-11 at 11 56 33 AM" src="https://github.com/user-attachments/assets/1fb9dc05-e674-4bac-9dc7-cdc398b07c14">

And indeed, if I take either of those `1`s in the stereo column and make it a `2`, the script runs fine.
