### ISSUE TITLE
Make ParameterX.__init__ functions require unit-attached parameters

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openff-toolkit#199]
So I've been having second thoughts about this (apologies for my original suggestion!), and I'm now wondering if we should have this signature in a `from_dict(permit_cosmetic_attributes=False. **kwargs)` static constructor, and keep a classic separate construct with a signature like `__init__(parameter_types=None, permit_cosmetic_attributes=False, ..., **cosmetic_attributes)` for consistency with the rest of the API.

_Originally posted by @andrrizzi in https://github.com/openforcefield/openforcefield/pull/173_

**Comment by mattwthompson** [comment]
I'm not sure this is strictly implemented in all cases, but I think in practical terms most of the force field loading infrastructure will choke with something is provided without units, i.e.

```python3
>>> from openff.toolkit.typing.engines.smirnoff.parameters import BondHandler
>>> BondHandler.BondType(length=4, k=10, smirks="")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mattthompson/software/openff-toolkit/openff/toolkit/typing/engines/smirnoff/parameters.py", line 2458, in __init__
    super().__init__(**kwargs)
  File "/Users/mattthompson/software/openff-toolkit/openff/toolkit/typing/engines/smirnoff/parameters.py", line 1748, in __init__
    super().__init__(allow_cosmetic_attributes=allow_cosmetic_attributes, **kwargs)
  File "/Users/mattthompson/software/openff-toolkit/openff/toolkit/typing/engines/smirnoff/parameters.py", line 855, in __init__
    setattr(self, key, val)
  File "/Users/mattthompson/software/openff-toolkit/openff/toolkit/typing/engines/smirnoff/parameters.py", line 1170, in __setattr__
    super().__setattr__(key, value)
  File "/Users/mattthompson/software/openff-toolkit/openff/toolkit/typing/engines/smirnoff/parameters.py", line 374, in __set__
    value = self._convert_and_validate(instance, value)
  File "/Users/mattthompson/software/openff-toolkit/openff/toolkit/typing/engines/smirnoff/parameters.py", line 390, in _convert_and_validate
    value = self._validate_units(value)
  File "/Users/mattthompson/software/openff-toolkit/openff/toolkit/typing/engines/smirnoff/parameters.py", line 410, in _validate_units
    raise IncompatibleUnitError(
openff.toolkit.utils.exceptions.IncompatibleUnitError: length=4 dimensionless should have units of angstrom
