### ISSUE TITLE
Topology.box_vectors setter allows dangerous usage

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openff-toolkit#638]
**Is your feature request related to a problem? Please describe.**
Box vectors is expected to be a 3x3 array. However, no error is raised if the the user provides a 1x3 list (assuming an already-defined orthonormal coordinate system)

**Current behavior**
```
from openforcefield.topology import Molecule
from simtk import unit

mol = Molecule.from_smiles('C')
top = mol.to_topology()
top.box_vectors = [[1,0,0], [0,1,0], [0,0,1]] * unit.angstrom
top.to_openmm()
```
works fine, but 
```

mol = Molecule.from_smiles('C')
top = mol.to_topology()
top.box_vectors = [1., 1., 1.] * unit.angstrom
top.to_openmm()
```
doesn't raise an error until the `top.to_openmm()` line

```
> > Traceback (most recent call last):
>   File "reproduce.py", line 14, in <module>
>     top.to_openmm()
>   File "/Users/jeffreywagner/projects/OpenForceField/openforcefield/openforcefield/topology/topology.py", line 1905, in to_openmm
>     omm_topology.setPeriodicBoxVectors(self.box_vectors)
>   File "/Users/jeffreywagner/miniconda3/envs/off-dev/lib/python3.7/site-packages/simtk/openmm/app/topology.py", line 245, in setPeriodicBoxVectors
>     if not is_quantity(vectors[0][0]):
>   File "/Users/jeffreywagner/miniconda3/envs/off-dev/lib/python3.7/site-packages/simtk/unit/quantity.py", line 733, in __getitem__
>     assert not is_quantity(self._value[key])
> TypeError: 'float' object is not subscriptable
```

**Describe the solution you'd like**
An informative error should be raised if someone tries to set `top.box_vectors` with a 1x3 array

**Comment by mattwthompson** [comment]
Another possible, overarching solution: don't store box vectors in the `Topology`, only store a `is_periodic` type of boolean, and store box vectors in the `System`.

**Comment by mattwthompson** [comment]
Re-opening this with a breaking case I found I did not cover with the earlier PR:

In: 
```python 3
# Load a molecule into the OpenFF Molecule object
from openff.toolkit.topology import Molecule
from openff.toolkit.utils import get_data_file_path
sdf_file_path = get_data_file_path('molecules/ethanol.sdf')
molecule = Molecule.from_file(sdf_file_path)

# Create an OpenFF Topology object from the molecule
from openff.toolkit.topology import Topology
topology = Topology.from_molecules(molecule)

# Set the box vectors with a list Quantity
from simtk import unit
topology.box_vectors = [4, 4, 4] * unit.nanometer

# Load the latest OpenFF force field definition
from openff.toolkit.typing.engines.smirnoff import ForceField
forcefield = ForceField('openff-1.2.0.offxml')

# Create an OpenMM system representing the molecule with SMIRNOFF-applied parameters
openmm_system = forcefield.create_openmm_system(topology)
```

Out:
```
Traceback (most recent call last):
  File "repro.py", line 20, in <module>
    openmm_system = forcefield.create_openmm_system(topology)
  File "/Users/mwt/software/openforcefield/openff/toolkit/typing/engines/smirnoff/forcefield.py", line 1301, in create_openmm_system
    system.setDefaultPeriodicBoxVectors(*topology.box_vectors)
  File "/Users/mwt/miniconda3/envs/openff-dev/lib/python3.7/site-packages/simtk/openmm/openmm.py", line 14457, in setDefaultPeriodicBoxVectors
    return _openmm.System_setDefaultPeriodicBoxVectors(self, a, b, c)
ValueError: in method System_setDefaultPeriodicBoxVectors, argument 2 could not be converted to type Vec3 const &
```

Checking `hasattr(, "shape")` works for unit-wrapped arrays, but not unit-wrapped lists

**Comment by mattwthompson** [comment]
Seems to be resolved now.
