### ISSUE TITLE
Unset public attributes in Topology

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openff-toolkit#784]
**Describe the bug**
Two (potentially more?) getters of `Topology` are wired up to point to attributes that don't exist. `Topology.fractional_bond_order_model` and `Topology.charge_model` have setters and getters, but neither are set in the `__init__` and do not seem to directly have a use in other classes. It looks like molecules know their charge model and force fields know their fractional bond order methods, but topologies are never asked if the have their own (at least in our tests - maybe some users care about this?). I couldn't find any open issues about these.

These could be set to `None`, set some default, or wired up to attempt to report a set of all models by iterating over the constituent molecules and bonds. But maybe it's better to remove them altogether? @j-wags do you envision these being _topology-level_ attributes in your preferred set of models? At very least I'd rather have a more descriptive exception that indicates its temporary state.

**To Reproduce**
```python3
>>> from openforcefield.topology import Molecule, Topology
>>> top = Topology.from_molecules(2 * [Molecule.from_smiles("CCO")])
>>> top.fractional_bond_order_model
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mwt/software/openforcefield/openforcefield/topology/topology.py", line 1496, in fractional_bond_order_model
    return self._fractional_bond_order_model
AttributeError: 'Topology' object has no attribute '_fractional_bond_order_model'
>>> top.charge_model
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mwt/software/openforcefield/openforcefield/topology/topology.py", line 1452, in charge_model
    return self._charge_model
AttributeError: 'Topology' object has no attribute '_charge_model'
```

**Output**
The full error message (may be large, that's fine. Better to paste too much than too little.)

**Computing environment (please complete the following information):**
 - Operating system:
 - Output of running `conda list`

**Additional context**
Specs for other classes than `ForceField`, like `Molecule` and `Topology`, might be useful to clear up some of these ambiguities, even if they're imperfect and not complete.

**Comment by mattwthompson** [comment]
Fixed, probably in #1213 

```python3
In [7]: top = Topology.from_molecules(2 * [Molecule.from_smiles("CCO")])

In [8]: top.fractional_bond_order_model
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [8], in <cell line: 1>()
----> 1 top.fractional_bond_order_model

AttributeError: 'Topology' object has no attribute 'fractional_bond_order_model'

In [9]: top.charge_model
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [9], in <cell line: 1>()
----> 1 top.charge_model

AttributeError: 'Topology' object has no attribute 'charge_model'
