### ISSUE TITLE
ForceField with programatic v-sites can't serialize

### ISSUE THREAD

**Issue by SimonBoothroyd** [openforcefield/openff-toolkit#884]
**Describe the bug**
A force which has programatic v-sites cannot be serialised as the V-site handler converts the special parameter list into a regular list.

**To Reproduce**

```
force_field = ForceField()

virtual_site_handler = force_field.get_parameter_handler("VirtualSites")
virtual_site_handler.add_parameter(
    {
        "smirks": "[#1:1]-[#8X2H2+0:2]-[#1:3]",
        "type": "DivalentLonePair",
        "distance": -0.0106 * unit.nanometers,
        "outOfPlaneAngle": 0.0 * unit.degrees,
        "match": "once",
        "charge_increment1": 1.0552 * 0.5 * unit.elementary_charge,
        "charge_increment2": 0.0 * unit.elementary_charge,
        "charge_increment3": 1.0552 * 0.5 * unit.elementary_charge,
    }
)

force_field.to_file("test.offxml")
```

**Output**

```
Traceback (most recent call last):
  File "/XXX/run.py", line 68, in <module>
    main()
  File "/XXX/run.py", line 30, in main
    force_field.to_file("test.offxml")
  File "/XXX/openff/toolkit/typing/engines/smirnoff/forcefield.py", line 1201, in to_file
    smirnoff_data = self._to_smirnoff_data(
  File "/XXX/openff/toolkit/typing/engines/smirnoff/forcefield.py", line 937, in _to_smirnoff_data
    l1_dict[handler_tag] = parameter_handler.to_dict(
  File "/XXX/openff/toolkit/typing/engines/smirnoff/parameters.py", line 2353, in to_dict
    parameter_list = self._parameters.to_list(
AttributeError: 'list' object has no attribute 'to_list'
```

**Computing environment (please complete the following information):**
 - Operating system:  OSX
 - Output of running `conda list`: TK = `0.9.1`

**Additional context**
N/A

**Comment by SimonBoothroyd** [comment]
cc @j-wags @trevorgokey

**Comment by j-wags** [comment]
I've reproduced the bug, and it's not limited to programmatic vsites. `ForceField` can't roundtrip the following OFFXML either:

```
x='''<?xml version="1.0" encoding="utf-8"?>
    <SMIRNOFF version="0.3" aromaticity_model="OEAroModel_MDL">
        <Bonds version="0.3" potential="harmonic" fractional_bondorder_method="AM1-Wiberg" fractional_bondorder_interpolation="linear">
          <Bond smirks="[*:1]~[*:2]" id="b999" k="500.0 * kilocalories_per_mole/angstrom**2" length="1.1 * angstrom"/>
        </Bonds>
        <VirtualSites version="0.3">
            <VirtualSite
                type="BondCharge"
                name="EP"
                smirks="[*:1]~[*:2]"
                distance="0.1*angstrom"
                charge_increment1="0.1*elementary_charge"
                charge_increment2="0.1*elementary_charge"
                sigma="0.1*angstrom"
                epsilon="0.1*kilocalories_per_mole"
                match="once" >
            </VirtualSite>
        </VirtualSites>
    </SMIRNOFF>
'''
from openff.toolkit.typing.engines.smirnoff import ForceField
ff = ForceField(x)
ff.to_string()
```
yields

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jeffreywagner/projects/OpenForceField/openff-toolkit/openff/toolkit/typing/engines/smirnoff/forcefield.py", line 1161, in to_string
    smirnoff_data = self._to_smirnoff_data(
  File "/Users/jeffreywagner/projects/OpenForceField/openff-toolkit/openff/toolkit/typing/engines/smirnoff/forcefield.py", line 937, in _to_smirnoff_data
    l1_dict[handler_tag] = parameter_handler.to_dict(
  File "/Users/jeffreywagner/projects/OpenForceField/openff-toolkit/openff/toolkit/typing/engines/smirnoff/parameters.py", line 2353, in to_dict
    parameter_list = self._parameters.to_list(
AttributeError: 'list' object has no attribute 'to_list'
```
