### ISSUE TITLE
Docs are failing to build

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openff-toolkit#902]
**Describe the bug**
https://readthedocs.org/projects/open-forcefield-toolkit/builds/13432629/

Seems to be happening for all builds. Probably an updated dependency. 

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/open-forcefield-toolkit/conda/762/lib/python3.7/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/open-forcefield-toolkit/conda/762/lib/python3.7/site-packages/sphinx/application.py", line 352, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/open-forcefield-toolkit/conda/762/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 298, in build_update
    len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/open-forcefield-toolkit/conda/762/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 310, in build
    updated_docnames = set(self.read())
  File "/home/docs/checkouts/readthedocs.org/user_builds/open-forcefield-toolkit/conda/762/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 417, in read
    self._read_serial(docnames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/open-forcefield-toolkit/conda/762/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 438, in _read_serial
    self.read_doc(docname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/open-forcefield-toolkit/conda/762/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 478, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/docs/checkouts/readthedocs.org/user_builds/open-forcefield-toolkit/conda/762/lib/python3.7/site-packages/sphinx/io.py", line 221, in read_doc
    pub.publish()
  File "/home/docs/checkouts/readthedocs.org/user_builds/open-forcefield-toolkit/conda/762/lib/python3.7/site-packages/docutils/core.py", line 218, in publish
    self.settings)
  File "/home/docs/checkouts/readthedocs.org/user_builds/open-forcefield-toolkit/conda/762/lib/python3.7/site-packages/sphinx/io.py", line 126, in read
    self.parse()
  File "/home/docs/checkouts/readthedocs.org/user_builds/open-forcefield-toolkit/conda/762/lib/python3.7/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/home/docs/checkouts/readthedocs.org/user_builds/open-forcefield-toolkit/conda/762/lib/python3.7/site-packages/myst_parser/sphinx_parser.py", line 195, in parse
    parser.renderer.render(tokens, parser.options, env)
  File "/home/docs/checkouts/readthedocs.org/user_builds/open-forcefield-toolkit/conda/762/lib/python3.7/site-packages/myst_parser/docutils_renderer.py", line 174, in render
    self.rules[f"render_{nest_token.type}"](nest_token)
  File "/home/docs/checkouts/readthedocs.org/user_builds/open-forcefield-toolkit/conda/762/lib/python3.7/site-packages/myst_parser/docutils_renderer.py", line 879, in render_colon_fence
    return self.render_fence(token)
  File "/home/docs/checkouts/readthedocs.org/user_builds/open-forcefield-toolkit/conda/762/lib/python3.7/site-packages/myst_parser/docutils_renderer.py", line 438, in render_fence
    MockRSTParser().parse(pseudosource, newdoc)
  File "/home/docs/checkouts/readthedocs.org/user_builds/open-forcefield-toolkit/conda/762/lib/python3.7/site-packages/myst_parser/mocking.py", line 493, in parse
    super().parse(inputstring, document)
  File "/home/docs/checkouts/readthedocs.org/user_builds/open-forcefield-toolkit/conda/762/lib/python3.7/site-packages/docutils/parsers/rst/__init__.py", line 196, in parse
    if len(line) > self.document.settings.line_length_limit:
AttributeError: 'Values' object has no attribute 'line_length_limit'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/open-forcefield-toolkit/conda/762/lib/python3.7/site-packages/docutils/parsers/rst/__init__.py", line 196, in parse
    if len(line) > self.document.settings.line_length_limit:
AttributeError: 'Values' object has no attribute 'line_length_limit'
The full traceback has been saved in /tmp/sphinx-err-8snpdbv1.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by j-wags** [comment]
Fixed by pinning `docutils==0.16` in #762
